# Generated by Django 5.0.7 on 2024-11-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='post_type',
            field=models.CharField(choices=[('Sell', 'Sell'), ('Rent', 'Rent')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='property_type',
        ),
    ]
