# Generated by Django 5.0.7 on 2024-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_post_type_delete_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='p_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
