# Generated by Django 5.0.7 on 2024-11-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_bath_property_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Houses', 'Houses'), ('Townhouses', 'Townhouses'), ('Condos', 'Condos'), ('Apartments', 'Apartments'), ('None', 'None')], default='None', max_length=100, null=True),
        ),
    ]
